liberapay: marcpartensky
patreon: marcpartensky
github: marcpartensky
custom:
  # - monero:43J2XmRtjDPRLD35UsYGH2AZamFBQz7dt4VdvZXVm3SuadTrvcoXUXBRUNHqukFte23Q5TWXqhbwaLJJgoVQzzbe2AJDANQ
  - https://paypal.me/marcpartensky
  - https://buymeacoffee.com/marcpartensky
