services:
  fourier:
    image: marcpartensky/fourier
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./FourierImages:/opt/FourierImages
      - ./FourierObjects:/opt/FourierObjects
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: $DISPLAY
    devices:
      - /dev/dri
    entrypoint: ./__main__.py rodolphe.jpg
